### ISSUE TITLE
esp32为啥不用晶振？

### ISSUE THREAD

**Issue by jumbo77** [peng-zhihui/HoloCubic#10]

**Comment by 88431844** [comment]
因为esp32-pico-D4已经集成40mhz晶振

**Comment by jumbo77** [comment]
第一次见有集成晶振的wifi芯片，不错，根本不用买模块了。芯片就是模块
之前用esp8266的晶体如果不是10ppm，wifi就不稳定

**Comment by 88431844** [comment]
> 第一次见有集成晶振的wifi芯片，不错，根本不用买模块了。芯片就是模块
> 之前用esp8266的晶体如果不是10ppm，wifi就不稳定

是，这个芯片我也是看稚辉君这个视频才知道，省去了很多外围电路
