### ISSUE TITLE
请问software文件夹里面的代码需要用什么软件编译

### ISSUE THREAD

**Issue by Aria-CYF** [peng-zhihui/HoloCubic#14]
如果小白我没理解错，firmware文件夹里面的文件是用arduino编译，那这个software是不是也要用arduino编译。如果是，他们是一起编译还是分开编译。

**Comment by peng-zhihui** [comment]
firmware是Arduino固件，software是visual studio的c++工程用于在电脑上模拟lvgl的ui界面，方便调试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Aria-CYF <notifications@github.com&gt;
发送时间: 2021年2月6日 12:10
收件人: peng-zhihui/HoloCubic <HoloCubic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[peng-zhihui/HoloCubic] 请问software文件夹里面的代码需要用什么软件编译 (#14)





 
如果小白我没理解错，firmware文件夹里面的文件是用arduino编译，那这个software是不是也要用arduino编译。如果是，他们是一起编译还是分开编译。

**Comment by Aria-CYF** [comment]
原来如此，非常感谢。
