### ISSUE TITLE
请教以下pcb中天线的设计？

### ISSUE THREAD

**Issue by cheng3100** [peng-zhihui/HoloCubic#15]
我看了下主板的pcb但是没有找到天线走线，如图，请问这个是藏在某个巧妙的地方了吗？还是说也可以不画？
![image](https://user-images.githubusercontent.com/25582840/107118669-40311c00-68bd-11eb-892b-fc04d3c267dd.png)

**Comment by Aria-CYF** [comment]
那个RAINSUN大概是天线

**Comment by WeiTian1026** [comment]
> 我看了下主板的pcb但是没有找到天线走线，如图，请问这个是藏在某个巧妙的地方了吗？还是说也可以不画？
> ![image](https://user-images.githubusercontent.com/25582840/107118669-40311c00-68bd-11eb-892b-fc04d3c267dd.png)

KainSun那个Component就是天线，集成天线。你说的那种是PCB天线。
