### ISSUE TITLE
请问有没有RAINSUN陶瓷天线的购买连接

### ISSUE THREAD

**Issue by Aria-CYF** [peng-zhihui/HoloCubic#16]
没有找到有关5120的型号。。。

**Comment by QY7** [comment]
淘宝上有AN2150，大小一样，可以用的

**Comment by Aria-CYF** [comment]
可是，我在淘宝只找到了AN2051，头疼。。。

**Comment by xingrz** [comment]
![image](https://user-images.githubusercontent.com/288288/108947422-61ef1900-769b-11eb-9761-8996d20e90e7.png)

![image](https://user-images.githubusercontent.com/288288/108947486-8519c880-769b-11eb-9c53-99cf86e5dcd4.png)

应该是这个，CrossAir CA-C03：https://item.taobao.com/item.htm?id=627328734225
