### ISSUE TITLE
SPI管脚设置

### ISSUE THREAD

**Issue by nonowhy** [peng-zhihui/HoloCubic#17]
esp32的SPI支持管脚映射，可以在setup时用void begin(int8_t sck=-1, int8_t miso=-1, int8_t mosi=-1, int8_t ss=-1);指定而不用去改那个spi的CPP文件
参考spi.h

**Comment by peng-zhihui** [comment]
本来就是用到了重映射啊，begin写在sd.cpp里，不改spi.cpp就得改sd.cpp，一样的。都是系统库，不如改spi一劳永逸



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: QwQ-jpg <notifications@github.com&gt;
发送时间: 2021年2月8日 18:28
收件人: peng-zhihui/HoloCubic <HoloCubic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[peng-zhihui/HoloCubic] SPI管脚设置 (#17)





 
esp32的SPI支持管脚映射，可以在setup时用void begin(int8_t sck=-1, int8_t miso=-1, int8_t mosi=-1, int8_t ss=-1);指定而不用去改那个spi的CPP文件
 参考spi.h

**Comment by QwQ-jpg** [comment]
是我疏忽了，漏了SD. begin了Ծ‸Ծ发自我的荣耀平板-------- 原始邮件 --------发件人： 稚晖 <notifications@github.com>日期： 2021年2月8日周一 晚上7:31收件人： peng-zhihui/HoloCubic <HoloCubic@noreply.github.com>抄送： QwQ-jpg <1942743313@qq.com>, Author <author@noreply.github.com>主    题： Re: [peng-zhihui/HoloCubic] SPI管脚设置 (#17)

本来就是用到了重映射啊，begin写在sd.cpp里，不改spi.cpp就得改sd.cpp，一样的。都是系统库，不如改spi一劳永逸















发自我的iPhone











------------------ 原始邮件 ------------------



发件人: QwQ-jpg <notifications@github.com&gt;



发送时间: 2021年2月8日 18:28



收件人: peng-zhihui/HoloCubic <HoloCubic@noreply.github.com&gt;



抄送: Subscribed <subscribed@noreply.github.com&gt;



主题: 回复：[peng-zhihui/HoloCubic] SPI管脚设置 (#17)























 



esp32的SPI支持管脚映射，可以在setup时用void begin(int8_t sck=-1, int8_t miso=-1, int8_t mosi=-1, int8_t ss=-1);指定而不用去改那个spi的CPP文件



 参考spi.h
