### ISSUE TITLE
请问这个错误是不是我找的MPU6050文件有问题

### ISSUE THREAD

**Issue by Aria-CYF** [peng-zhihui/HoloCubic#18]
1、这里显示两个变量没有定义，是不是我找的MPU6050文件有问题，可以的话请大佬发一下这个文件夹。
2、这里出现了重复库会不会影响最后的编译结果。
3、安装完esp32的支持包后，出现很多开发板的选项，请问编译的时候需要选择哪一个。

`E:\Arduino\libraries\MPU6050\MPU6050.cpp: In member function 'int8_t MPU6050::GetCurrentFIFOPacket(uint8_t*, uint8_t)':
E:\Arduino\libraries\MPU6050\MPU6050.cpp:2763:32: error: 'BUFFER_LENGTH' was not declared in this scope
                  uint8_t Trash[BUFFER_LENGTH];
                                ^
E:\Arduino\libraries\MPU6050\MPU6050.cpp:2769:39: error: 'Trash' was not declared in this scope
                          getFIFOBytes(Trash, (uint8_t)RemoveBytes);
                                       ^

"WiFi.h" 对应多个库
 已使用： E:\Arduino\hardware\espressif\esp32\libraries\WiFi
 未使用：E:\Arduino\libraries\WiFi

"SD.h" 对应多个库
 已使用： E:\Arduino\hardware\espressif\esp32\libraries\SD
 未使用：E:\Arduino\libraries\SD

exit status 1
为开发板 ESP32 Dev Module 编译时出错。`

**Comment by AsahiEast** [comment]
在MPU6050.h文件里补一句`#define BUFFER_LENGTH 32`
