### ISSUE TITLE
钢铁侠版本MainBoard嘉利创打板无法解析成功

### ISSUE THREAD

**Issue by superstarQ** [peng-zhihui/HoloCubic#21]
是不是PCB哪里有问题呢，

**Comment by peng-zhihui** [comment]
不用管，他们软件的问题额，直接提交就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SuperNovaHQ <notifications@github.com&gt;
发送时间: 2021年2月19日 13:10
收件人: peng-zhihui/HoloCubic <HoloCubic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[peng-zhihui/HoloCubic] 钢铁侠版本MainBoard嘉利创打板无法解析成功 (#21)





 
是不是PCB哪里有问题呢，
