### ISSUE TITLE
图片转换应该选择Indexed 16 colors

### ISSUE THREAD

**Issue by lmf-bit** [peng-zhihui/HoloCubic#29]

**Comment by xusixteen** [comment]
Indexed 4 colors和Indexed 16 colors转换了效果一样。何解？
![100](https://user-images.githubusercontent.com/31234222/111304422-afeeaf80-8690-11eb-87ab-8cc8fd8dd8c2.png)
![100](https://user-images.githubusercontent.com/31234222/111304436-b2e9a000-8690-11eb-96ba-69420b2e63ab.png)

**Comment by Aria-CYF** [comment]
请问用什么软件转换图片成16进制
