### ISSUE TITLE
能否加入原理图和PCB的PDF文档

### ISSUE THREAD

**Issue by ZestyXin** [peng-zhihui/HoloCubic#3]
由于我的主力电脑是Linux，无法安装AD。且不想通过虚拟机的方式安装AD。不知能够提供生成原理图和PCB的PDF文档？
如果可以的话能为之前的项目和日后的项目也一并提供PDF文档吗？

**Comment by peng-zhihui** [comment]
添加了

发送自 Windows 10 版邮件应用

发件人: ZestyXin
发送时间: 2021年1月25日 上午 11:39
收件人: peng-zhihui/HoloCubic
抄送: Subscribed
主题: [peng-zhihui/HoloCubic] 能否加入原理图和PCB的PDF文档 (#3)

由于我的主力电脑是Linux，无法安装AD。且不想通过虚拟机的方式安装AD。不知能够提供生成原理图和PCB的PDF文档？
如果可以的话能为之前的项目和日后的项目也一并提供PDF文档吗？

**Comment by ZestyXin** [comment]
谢谢
