### ISSUE TITLE
arduino IDE 端口灰色，无法选择，是板子没有焊好还是电脑驱动没装好

### ISSUE THREAD

**Issue by w-wu14** [peng-zhihui/HoloCubic#31]

**Comment by w-wu14** [comment]
已安装CP201x驱动，但是端口呈现灰色，无法选择，是板子没有焊好还是有其它原因，求指点

**Comment by diystring** [comment]
就是 cp201x 芯片没焊接好，USB 都还没识别出芯片

**Comment by w-wu14** [comment]
> 就是 cp201x 芯片没焊接好，USB 都还没识别出芯片

感谢大佬回复，请问如何判断2012芯片是否焊接好了。我焊接时轻轻拨动芯片，有归位的动作，外部引脚也没有连锡的情况。输出的VDD是3.3V 电源地也没有短路，D+ D- 是低电平。想问一下还需要看哪几个管脚的信号，焊接正常应该输出什么电压？

**Comment by diystring** [comment]
找块新板子只焊接 usb和201x 芯片以及电路，插在电脑上，管理工具里的端口 就能识别到，如果不能识别要么就是焊接问题要么就是芯片本身有问题

**Comment by w-wu14** [comment]
> 找块新板子只焊接 usb和201x 芯片以及电路，插在电脑上，管理工具里的端口 就能识别到，如果不能识别要么就是焊接问题要么就是芯片本身有问题

第二块板子只焊了CP2012相关的电路 但是还是无法识别，不太确定是芯片的问题还是焊接的问题了，感觉还是要从芯片的输出管脚判断芯片功能是否正常

**Comment by w-wu14** [comment]
最终确认是CP2012芯片的问题了，换了一家就可以了
