### ISSUE TITLE
（不妥请删除）请问到底哪个是您的ytb账号，还是这两个都是李鬼在冒充

### ISSUE THREAD

**Issue by markmingjie** [peng-zhihui/HoloCubic#39]
![image](https://user-images.githubusercontent.com/34265999/111981242-60056200-8b42-11eb-803f-2add29b7dd79.png)

**Comment by peng-zhihui** [comment]
彭稚晖是我，看早期发的视频就知道了哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: markmingjie ***@***.***&gt;
发送时间: 2021年3月22日 19:12
收件人: peng-zhihui/HoloCubic ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[peng-zhihui/HoloCubic] （不妥请删除）请问到底哪个是您的ytb账号，还是这两个都是李鬼在冒充 (#39)

**Comment by markmingjie** [comment]
感谢回复！

> 彭稚晖是我，看早期发的视频就知道了哈 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: markmingjie ***@***.***&gt; 发送时间: 2021年3月22日 19:12 收件人: peng-zhihui/HoloCubic ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[peng-zhihui/HoloCubic] （不妥请删除）请问到底哪个是您的ytb账号，还是这两个都是李鬼在冒充 (#39) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
