### ISSUE TITLE
有大佬能教我一下这个怎么做吗

### ISSUE THREAD

**Issue by EasonLYZ** [peng-zhihui/HoloCubic#93]
我用的是VsCode，我想修改下面这个
![image](https://github.com/peng-zhihui/HoloCubic/assets/98304327/fba448b2-8188-4f53-9fdb-31d91f70d16d)
有谁能教我这个在VsCode中怎么做到的吗？

**Comment by MikasaDov** [comment]
在
![image](https://github.com/peng-zhihui/HoloCubic/assets/131223386/b152f2a1-986e-4e25-8d07-91f5f9a87fba)
sd_card.h文件中 #include 了SPI.h
点进去随便找个函数转到定义
![image](https://github.com/peng-zhihui/HoloCubic/assets/131223386/dd158ff9-e1ac-4471-aad0-bd29a2ed436f)
就到SPI.cpp文件里了
